/*import './alertas.js';
import './auth.js';
import './evento.js'
import './horas.js';
import './ponente.js';
import './ponentesEvento.js';
import './principal.js';
import './slider.js';
import './tags.js';*/